# Generated by Django 5.0.5 on 2024-05-14 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_quarto_foto_quarto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='descricao',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='quarto',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quarto',
            name='titulo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='foto_quarto',
            field=models.ImageField(upload_to='quartos/'),
        ),
    ]
